services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ci_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN_CI}
    networks:
      - ci_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    environment:
      - TZ=Asia/Jakarta
      - JAVA_OPTS=-Xmx1024m -Duser.timezone=Asia/Jakarta
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - ci_network
    deploy:
      resources:
        limits:
          memory: 2G

networks:
  ci_network:
    driver: bridge

volumes:
  jenkins_data: